### ISSUE TITLE
How to put animals into the hemogen extractor ?

### ISSUE THREAD

**Issue by Yu-457** [eth0net/AnimalHemogen#1]
Hi there, 
ive been adding this mod to my game. So far everything seems to work fine. I do see the extractor action on the animals. But i do not see any option to put animals into the hemogen extractor. 
Could you maybe tell me where im supposed to find that one ?
Right clicking on the animal didnt show anyting for me, i did not see any option on the extractor either :S 

Thanks a lot in advance

**Comment by eth0net** [comment]
Glad to hear you like it and it seems to be working 😃 

To add an animal to the extractor they will need to be downed I believe, I'll double check when I'm at my PC later! So you'll have to melee them until they go down, or find some other way to knock them down.

**Comment by eth0net** [comment]
Tested it again and you do indeed knock them down, then get a pawn to take them to the extractor. Hope this helps 😄

**Comment by Yu-457** [comment]
@eth0net  oh lol, i did not expect that :D i will try this evening. 
I've only tried to put my farm animals so far
thanks a lot :)

**Comment by eth0net** [comment]
I'll also experiment a little more and see if there's a decent way to allow putting tame animals in without downing them 😄
